name: Hello World

# Trigger options (manual)
on: 
  push:
    branches:
      - development
      - 'release/**'
  pull_request:
    branches: main
# Jobs are configured here (Runs default parallely )
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Phase
        run: echo "Building project....."
 