name: Hello World

# Trigger options (manual)
on: 
  push:
    branches:
      - development
      - 'release/**'
  pull_request:
    branches: main
# Jobs are configured here (Runs default parallely )
jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: variable phase
        run: echo "Hello, ${{vars.MY_NAME}} how are you doing..."
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: secrets phase
        run: echo "Hello, ${{secrets.DOCKER_HUB_PASSWD}} how are you doing..."
  

 