name: Hello World

# Trigger options (manual)
on: 
  push:
    branches:
      - development
      - 'release/**'
  pull_request:
    branches: main
# Jobs are configured here (Runs default parallely )
jobs:
  checkout_code:
    runs-on: ubuntu-slim
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: print index.html file
        run: cat index.html

  

 