name: Hello World

# Trigger options (manual)
on: 
  push:
    branches: main

# Jobs are configured here (Runs default parallely )
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Phase
        run: echo "Building project....."
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Phase
        run: echo "Running test cases...."
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Phase
        run: echo "Deploying the project...."